name: Build Deploy

#
# CI/CD workflow that runs on Git pushes and builds and deploys this app to Heroku.
#

on:
  push:
    branches:
      - master

# all env vars must be configured as config vars in Heroku pipeline settings

defaults:
  run:
    shell: bash

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: '11'
      - name: Push to Heroku Git to trigger build and deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: mule-secure-props-tool-slack
          heroku_email: gerald.loeffler@googlemail.com
          dontautocreate: true
          healthcheck: https://mule-secure-props-tool-slack.herokuapp.com/q/health/ready
          delay: 10
